name: 🧲 Provider Request
description: Template for bug reports
title: '[Provider] '
labels:
  - provider
  - request
body:
  - type: input
    id: provider
    attributes:
      label: Provider
      description: Name of the DNS provider you are requesting support for.
      placeholder: e.g. Google Cloud Platform
    validations:
      required: true
  - type: input
    id: api
    attributes:
      label: API Documentation
      description: Link to the API documentation for the DNS provider.
      placeholder: e.g. https://cloud.google.com/dns/docs/reference/v1
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: >-
        Explain why adding support for this provider would be beneficial to the
        project and its users.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the provider request here.
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
